const carta =[`\nENTRADAS`,
`\n Chorizo 1500$`,
`\n Morcilla 1200$`,
`\n Matrimonio 2300$ (1 chorizo y 1 morcilla)`,
`\n Provoleta de la casa 2700$`,
`\n Chinchulines 1400$`,
`\n Empanadas 700$ (empanada de carne a cuchillo o J&Q fritas)` ,
`\n Mollejas con crema 3300$ Mollejas a la parrilla con salsa de crema`,
`\n Aros de cebolla 1800$`,
`\n Mix de achuras 3800$ ½ chorizo ½ morcilla ½ porción de chinchulines y 1 provoleta`,
`\n ASADO`,
`\n Pata-muslo con manteca de hierbas 4000$`,
`\n Entraña 5000$`,
`\n Vacío 4500$`,
`\n Costillar 6500$`,
`\n Porter-house 5600$`,
`\n T-bone 5200$`,
`\n Matambre de cerdo 4000$`,
`\nAHUMADOS`,
`\n Ribs a la barbacoa 6500$`,
`\n Bondiola con reducción de cerveza negra 6000$`,
`\n Sándwich de brisket ahumado 3500$ `,
`\n PARRILLADA`,
`\n de la casa 11000$ (entraña, bondiola, porter-house, provoleta, chorizo y una ensalada a elección)`  , 
`\n Ahumada 9800$ (ribs a la barbacoa, bondiola con reducción de cerveza negra, morcilla y una ensalada a elección)`,
`\n COCINA`,
 `\n Ravioles con salsa 3300$ (crema, pure de tomate o mezcla)` ,  
`\n Pasta caccio e pepe 3600$ (veggie) (tagliatelle con salsa de queso y pimienta)`,
`\n Pechuga de pollo rellena de queso azul 3000$ (viene con acompañamiento)`,
`\n Milanesa de pollo con bechamel y quesos 3500$ (viene con acompañamiento)`,
`\n Milanesa de carne 2800$ (viene con acompañamiento)`,
`\n ACOMPAÑAMIENTOS`,
`\n Papas fritas 1000$`,
`\n Batatas fritas 1200$`,
`\n Pure de papa 1200$`,
`\n Papas a caballo 1800$`,
`\n Ensalada de 4 verduras 1000$`,
`\n Dos huevos fritos 800$`,
` \n TRAGOS`,
`\n Gin tonic 18002800$
`,
`\n Negroni 1800$` ,
`\n Aperol sprit 1800$`,
`\n Americano 1800$`,
`\n Fernet con cola 1800$`,
`\n POSTRES`,
`\n Creme brulee 2800$`,
`\n Flan con crema, dulce o mixto 2300$`,
`\n Brownie con helado 3200$`,
`\n Crumble de manzana 3300$`,
`\n Cheesecake de frutos rojos 3500$` ,  
`\n VINOS`,
`\n Copa de vino 2000$ (malbec, merlot o Cabernet Sauvignon)`,
`\n Botella de Malbec 4000$`,
`\n Botella de Cabernet Sauvignon 4000$`,
`\n Botella de Pinot noir 4000$`,
`\n Botella de Merlot 4000$`,
`\n Botella de Rosado 4500$`,
`\n Botella de Espumante 5500$`,
]
const dias = [
   `martes`,
   ` miercoles`,
   ` jueves`,
   ` viernes`,
   ` sabados`,
   ` domingos`,
   ]
const pasos = [
       `1° Tabla de quesos y salames curados`,
       `2° brochetas de carne y vegetales grillados`,
       `3° porterhouse a las brazas con ensalada de verdes`,
       `4° creme brûlée`,
   ]
   const numero = 1127700861;